param(
    [string]$InputPath  = (Join-Path $PSScriptRoot 'g25-distance-modern.txt'),
    [string]$OutputPath = (Join-Path $PSScriptRoot 'import_g25_distance_modern.sql'),
    [string]$EraName    = 'Modern Era (2000' + [char]0x2013 + '2026 AD)',
    [string]$Creator    = 'data-import-modern'
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $InputPath)) { throw "Input not found: $InputPath" }

$lines = Get-Content -LiteralPath $InputPath -Encoding UTF8
$rows  = New-Object System.Collections.Generic.List[string]

foreach ($line in $lines) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    $commaIdx = $line.IndexOf(',')
    if ($commaIdx -lt 1) { throw "Malformed line: $line" }

    $label  = $line.Substring(0, $commaIdx).Trim()
    $coords = $line.Substring($commaIdx + 1).Trim()
    if ($label.Length -eq 0 -or $coords.Length -eq 0) { continue }

    # Escape single quotes for SQL literals by doubling them
    $labelEscaped  = $label  -replace "'", "''"
    $coordsEscaped = $coords -replace "'", "''"

    [void]$rows.Add("  ('$labelEscaped', '$coordsEscaped')")
}

$eraNameEscaped = $EraName -replace "'", "''"
$creatorEscaped = $Creator -replace "'", "''"

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("-- Auto-generated by generate_g25_distance_modern_import.ps1")
[void]$sb.AppendLine("-- Source: g25-distance-modern.txt")
[void]$sb.AppendLine("-- Rows: $($rows.Count)")
[void]$sb.AppendLine("-- Target era: $EraName")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("BEGIN;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("DO `$`$")
[void]$sb.AppendLine("DECLARE")
[void]$sb.AppendLine("    v_era_id   integer;")
[void]$sb.AppendLine("    v_now      timestamptz := NOW();")
[void]$sb.AppendLine("    v_inserted integer;")
[void]$sb.AppendLine("BEGIN")
[void]$sb.AppendLine("    SELECT ""Id"" INTO v_era_id")
[void]$sb.AppendLine("    FROM g25_distance_eras")
[void]$sb.AppendLine("    WHERE ""Name"" = '$eraNameEscaped';")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    IF v_era_id IS NULL THEN")
[void]$sb.AppendLine("        RAISE EXCEPTION 'G25 distance era ""%"" not found', '$eraNameEscaped';")
[void]$sb.AppendLine("    END IF;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    INSERT INTO g25_distance_population_samples")
[void]$sb.AppendLine("      (""Label"", ""Coordinates"", ""Ids"", ""G25DistanceEraId"",")
[void]$sb.AppendLine("       ""CreatedAt"", ""CreatedBy"", ""UpdatedAt"", ""UpdatedBy"")")
[void]$sb.AppendLine("    SELECT v.label, v.coords, '', v_era_id,")
[void]$sb.AppendLine("           v_now, '$creatorEscaped', v_now, '$creatorEscaped'")
[void]$sb.AppendLine("    FROM (VALUES")
[void]$sb.Append(($rows -join ",`r`n"))
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    ) AS v(label, coords);")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    GET DIAGNOSTICS v_inserted = ROW_COUNT;")
[void]$sb.AppendLine("    RAISE NOTICE 'Inserted % population samples for era id % (%)', v_inserted, v_era_id, '$eraNameEscaped';")
[void]$sb.AppendLine("END")
[void]$sb.AppendLine("`$`$;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("COMMIT;")

Set-Content -LiteralPath $OutputPath -Value $sb.ToString() -Encoding UTF8
Write-Host "Wrote $OutputPath ($($rows.Count) rows)"
