using Odin.Api.Data.Enums;

namespace Odin.Api.Endpoints.AncestralPortraitManagement;

/// <summary>
/// Built-in, GENDER-SPECIFIC "ancestral self" scenes for each seeded qpAdm population — the period-accurate dress,
/// adornments and full-bleed cultural background the user is reimagined into for the paid "Through the Ages" add-on.
/// Keyed by the population's exact <see cref="Data.Entities.QpadmPopulation.Name"/>; each entry carries a MALE and a
/// FEMALE variant. The women's attire is independently period-researched (documented garments, headwear, hairstyle
/// and jewellery for that culture) — NOT a recoloured men's outfit, and women are not placed in men's armour unless
/// the culture attests it. <see cref="AncestralPortraitPrompts"/> uses these as the curated creative whenever a
/// population has no admin-set <c>QpadmPopulation.ImagePrompt</c> override (that override still wins), so the portrait
/// resembles the population's own photo instead of the bare name+description fallback. These are intentionally
/// distinct from the male-only avatar scenes in the FE manifest <c>POPULATION_IMAGE_PROMPTS</c>, which drive the
/// population AVATARS (always a man), not these identity-preserving, gendered user portraits.
/// </summary>
internal static class AncestralPortraitScenes
{
    /// <summary>
    /// When <paramref name="populationName"/> has a built-in scene, sets <paramref name="scene"/> to the
    /// gender-appropriate variant and returns true. Female → the women's variant; Male or null → the men's variant.
    /// </summary>
    public static bool TryGetScene(string? populationName, Gender? gender, out string scene)
    {
        if (populationName is not null && Scenes.TryGetValue(populationName.Trim(), out var variants))
        {
            scene = gender == Gender.Female ? variants.Female : variants.Male;
            return true;
        }

        scene = string.Empty;
        return false;
    }

    /// <summary>Population name → (men's scene, women's scene). Names match Data/SeedData/qpadm-populations.json.</summary>
    private static readonly IReadOnlyDictionary<string, (string Male, string Female)> Scenes =
        new Dictionary<string, (string Male, string Female)>(StringComparer.OrdinalIgnoreCase)
        {
            ["Anatolian Neolithic Farmer (8500 - 6000 BC)"] = (
                "A man of central Anatolia in the time of the first farmers (c. 8500-6000 BCE), wearing simple hand-woven garments of wool and tree-bast fibre in plain tabby weave, with a few bone and clay ornaments and pierced-stone beads. The full-bleed background is the world of the earliest agriculturalists: clustered mud-brick houses entered by rooftop ladders in the Çatalhöyük manner, plastered interior walls painted with aurochs and leaping bull motifs, sheaves of einkorn wheat and barley, a hafted flint sickle and a stone grinding quern, domesticated sheep and goats, hand-built painted pottery and a seated clay figurine, glossy obsidian blades, with the Anatolian plateau and distant volcanic cones beyond.",
                "A woman of central Anatolia in the time of the first farmers (c. 8500-6000 BCE), in a hand-woven wool-and-tree-bast garment of plain tabby weave: a spotted leopard-motif top and a wrapped fringed skirt after the Çatalhöyük figurines, her skin patterned with red ochre, adorned with strings of stone, shell, bone and clay beads, carved pendants and a bracelet, hair gathered. The full-bleed background is the first farmers' world: clustered mud-brick houses entered by rooftop ladders in the Çatalhöyük manner, plastered walls painted with aurochs and leaping bulls, sheaves of einkorn wheat and barley, a hafted flint sickle and stone grinding quern, sheep and goats, painted pottery and a seated clay figurine, glossy obsidian blades, and the Anatolian plateau with distant volcanic cones beyond."),
            ["Western Steppe Herder (5000 - 2800 BC)"] = (
                "A man of the Western Steppe Herders of the Pontic-Caspian steppe (Yamnaya culture, c. 3300-2600 BCE), a tall, robust adult, his hair tied back and his skin dusted with red ochre, wearing wool-and-leather garments under a heavy sheepskin cloak with a few bone and copper ornaments. The full-bleed background is the herder's world: rolling open grassland under a vast sky, a herd of cattle and shaggy horses, a heavy four-wheeled ox-drawn wooden wagon, a grassy kurgan burial mound on the horizon, corded-ware pottery, a copper axe, and hide tents beside a smouldering campfire.",
                "A woman of the Western Steppe Herders of the Pontic-Caspian steppe (Yamnaya culture, c. 3300-2600 BCE), a high-status adult, her skin dusted with red ochre and her hair bound back, in an undyed wool-and-hide gown edged with strands of bone, shell and stone beads and deer-tooth and boar-tusk pendants sewn along the hems, a copper-bead necklace, carved bone hammer-shaped pins at her shoulders and copper temple-ring ornaments by her brow. The full-bleed background is the herder's world: rolling open grassland under a vast sky, a herd of cattle and shaggy horses, a heavy four-wheeled ox-drawn wooden wagon, a grassy kurgan burial mound on the horizon, corded-ware pottery, a copper axe, and hide tents beside a smouldering campfire."),
            ["Western Hunter Gatherer (12000 - 6000 BC)"] = (
                "A man of Mesolithic Europe (c. 12,000-6,000 BCE), lean and weathered, his face marked with red ochre, wearing stitched animal-hide garments and strung necklaces of pierced shells, red-deer canine teeth and amber. The full-bleed background is the forager's world: dense temperate forest beside a still lake, a hunted red deer and a wild boar, a bow with flint-tipped arrows and a barbed antler harpoon, scattered microlith blades, a dugout canoe drawn up at the water's edge, and a hide shelter beside a smouldering fire.",
                "A woman of Mesolithic Europe (c. 12,000-6,000 BCE), lean and weathered, her face marked with red ochre, wearing a wrapped, stitched soft-hide dress with a fringed hem and a beaded hide cap and headband; rows of perforated Columbella and Glycymeris shells and red-deer canine teeth are sewn onto her bodice, sleeves and a hide belt, and amber pendants and elk-tooth strands hang at her throat. The full-bleed background is the forager's world: dense temperate forest beside a still lake, a hunted red deer and a wild boar, a bow with flint-tipped arrows and a barbed antler harpoon, scattered microlith blades, a dugout canoe drawn up at the water's edge, and a hide shelter beside a smouldering fire."),
            ["Eastern Hunter Gatherer (12000 - 5000 BC)"] = (
                "A man of the Mesolithic forest-steppe (c. 12,000-5,000 BCE, Lake Onega and the Volga-Urals), in thick layered fur and stitched hide garments with a fur-trimmed hood, strung with bone beads and rows of elk-tooth pendants, a smear of red ochre across his brow. The full-bleed background is the taiga forager's world: pine-and-birch forest meeting open rolling steppe, a great cold northern lake, a hunted elk and reindeer, a bone-tipped spear and a barbed antler harpoon, slate and antler tools, a dugout canoe drawn up at the shore, fishing nets hung to dry on wooden frames, and a fur-covered shelter beside a low fire.",
                "A woman of the Mesolithic forest-steppe (c. 12,000-5,000 BCE, Lake Onega and the Volga-Urals), in a long stitched hide-and-fur dress and fur-trimmed cloak whose hem, breast and belt are densely sewn with hundreds of rattling Eurasian elk-incisor pendants, a fur-and-hide headdress fringed with the same teeth and bone beads, strands of amber and shell beads at her throat, red ochre dusting her brow. The full-bleed background is the taiga forager's world: pine-and-birch forest meeting open rolling steppe, a great cold northern lake, an elk and grazing reindeer, a bone-tipped spear and barbed antler harpoon, slate and antler tools, a dugout canoe at the shore, fishing nets drying on wooden frames, and a fur-covered shelter beside a low fire."),
            ["Caucasian Hunter Gatherer (13000 - 7000 BC)"] = (
                "A man of the southern Caucasus foragers (c. 13,000-7,000 BCE, the Satsurblia and Kotias caves of Georgia), an adult hunter with long hair and a full beard, wearing stitched animal hides and woven plant-fibre wraps belted at the waist, strung with pendants of perforated animal teeth and bone and a few shell beads. The full-bleed background is the mountain forager's world: steep wooded Caucasus slopes and a dark cave mouth, a hunted wild tur (mountain goat) and a red deer, flint and obsidian blades, bone awls and a hafted spear, coils of twisted flax cordage, and a hearth glowing inside the rock shelter.",
                "A woman of the southern Caucasus foragers (c. 13,000-7,000 BCE, the Satsurblia and Kotias caves of Georgia), an adult of the band with her hair plaited back, wearing a wrapped dress of woven flax dyed in muted plant colours (ochre-red, yellow, brown) over softened hides, bound with twisted flax cordage, and adorned with strings of perforated red-deer teeth, polished bone and shell pendants at neck and brow. The full-bleed background is the mountain forager's world: steep wooded Caucasus slopes and a dark cave mouth, a hunted wild tur (mountain goat) and a red deer, flint and obsidian blades, bone awls and a hafted spear, coils of twisted flax cordage, and a hearth glowing inside the rock shelter."),
            ["Iranian Neolithic Farmer (8000 - 5000 BC)"] = (
                "A man of the Zagros highland farmers (c. 8000-5000 BCE, Ganj Dareh) wearing undyed homespun wool and goat-hair garments, plainly cut and belted, with simple bone ornaments and a few strung shell-and-stone beads at the throat. The full-bleed background is the highland farmer's world: terraced mud-brick dwellings clustered in a Zagros valley, a herd of newly domesticated goats, sheaves of barley and emmer wheat, a stone grinding quern and plastered storage bins, small clay counting tokens, coarse hand-formed pottery, and rugged mountain ridges beyond.",
                "A woman of the Zagros highland farmers (c. 8000-5000 BCE, Ganj Dareh) wearing an undyed homespun wool and goat-hair wrap, plain plain-weave cloth draped and belted at the waist, a simple woven headcloth over plaited bound hair, and her only ornaments strands of imported sea-shell and polished stone beads with a single drilled stone pendant - the modest adornment of an egalitarian village with no rank or finery. The full-bleed background is the highland farmer's world: terraced mud-brick dwellings clustered in a Zagros valley, a herd of newly domesticated goats, sheaves of barley and emmer wheat, a stone grinding quern and plastered storage bins, small clay counting tokens, coarse hand-formed pottery, and rugged mountain ridges beyond."),
            ["Natufian (12000 - 8000 BC)"] = (
                "A man of the Epipaleolithic Levant (c. 12,000-8,000 BCE), one of the first sedentary foragers, wearing a fitted hide garment and a headband and headdress sewn with rows of dentalium tusk-shells, with layered necklaces of dentalium beads, bone pendants and fox-teeth across his chest. The full-bleed background is the Natufian world: round semi-subterranean stone-walled houses roofed with brush, wild stands of einkorn and barley with a hafted flint sickle, deep stone mortars and pestles, bone fish-hooks and shell beads, a hunted gazelle at the field edge, a domesticated dog resting at his side, and the dry rolling Levantine hills beyond.",
                "A woman of the Epipaleolithic Levant (c. 12,000-8,000 BCE), one of the first sedentary foragers, wearing a soft hide garment and an elaborate close-fitting cap and headdress densely sewn with rows of dentalium tusk-shells, a broad pectoral cluster of dentalium beads, bird-bone tube beads and tusk-shell spacers across her chest, strung pendants of carved gazelle phalanx bones, and a girdle of dentalium shells at her waist. The full-bleed background is the Natufian world: round semi-subterranean stone-walled houses roofed with brush, wild stands of einkorn and barley with a hafted flint sickle, deep stone mortars and pestles, bone fish-hooks and shell beads, a hunted gazelle at the field edge, a domesticated dog resting nearby, and the dry rolling Levantine hills beyond."),
            ["North African Farmer (5200 - 4000 BC)"] = (
                "A man of the North African Neolithic Maghreb (c. 5200-4000 BCE), an adult male farmer-herder in a wrapped tunic of woven wool and softened hide, belted at the waist, with a hide mantle over one shoulder; he wears strands of ostrich-eggshell disc beads and pierced marine-shell ornaments at his neck, bone pendants, and a faint dusting of red ochre on his brow. The full-bleed background is the Maghreb farmer's world filling the frame edge to edge: a coastal cave camp sheltered below the Atlas foothills, mingled herds of sheep, goats and cattle, impressed Cardial-ware pottery, hafted flint sickles and flat grinding stones, loose sheaves of harvested grain, drying skins, and the Mediterranean shore meeting dry sun-baked hills under a bright sky.",
                "A woman of the North African Neolithic Maghreb (c. 5200-4000 BCE), an adult female farmer-herder in a wrapped, draped dress of woven wool and softened hide pinned at one shoulder and gathered with a woven belt, a hide shawl across her back; her hair is in fine Maghrebi braids bound with bone pins, and she wears ostrich-eggshell disc beads, cowrie and Nassarius shell necklaces, and red ochre on her brow. The full-bleed background is the Maghreb farmer's world filling the frame edge to edge: a coastal cave camp sheltered below the Atlas foothills, mingled herds of sheep, goats and cattle, impressed Cardial-ware pottery, hafted flint sickles and flat grinding stones, loose sheaves of harvested grain, drying skins, and the Mediterranean shore meeting dry sun-baked hills under a bright sky."),
            ["Northeast Asian (6000 - 2000 BC)"] = (
                "A man of Holocene Siberia (c. 6000-2000 BCE, the Altai and Trans-Baikal) — a hunter wearing a thick tailored fur parka with a fur-lined hood and hide boots, strung with bone and antler ornaments and pierced animal-tooth pendants. The full-bleed background is the Siberian world: snow-dusted taiga forest meeting open tundra under a pale cold sky, a grazing reindeer herd and a hunted elk, a composite bow and a bone-tipped harpoon leaning as scenery, a lashed wooden sledge, fish drying on wooden racks, a conical skin tent with its flap lifting, and a shaman's antler talisman by a low fire.",
                "A woman of Holocene Siberia (c. 6000-2000 BCE, the Altai and Trans-Baikal) — of elite standing in a tailored fur and hide garment with a fur-lined hood, richly adorned in the manner of the Cis-Baikal Neolithic dead: layered collars and strands of polished bone and antler tubular beads, pierced animal-tooth and shell pendants, and a bead-sewn hide bodice. The full-bleed background is the Siberian world: snow-dusted taiga forest meeting open tundra under a pale cold sky, a grazing reindeer herd and a hunted elk, a composite bow and a bone-tipped harpoon leaning as scenery, a lashed wooden sledge, fish drying on wooden racks, a conical skin tent with its flap lifting, and a shaman's antler talisman by a low fire."),
            ["Native American (15000 - 1500 BC)"] = (
                "A man of the late Pleistocene–Archaic Americas (c. 15,000–1500 BCE), descended from the first Beringian founders, his long straight hair worn loose and his face touched with ochre, wearing fringed soft-tanned hide garments with a hide cloak and ornaments of bone, shell and eagle feather, a beaded necklace of pierced shell and animal teeth. The full-bleed background is the First Americans' world: a vast wild landscape of open plains, woodland and distant snow-capped peaks, a herd of hunted bison and caribou drifting across the grass, an atlatl spear-thrower with fluted stone points leaning ready, conical hide tents, a campfire with strips of meat drying on wooden racks, and migratory game moving along the far horizon under a wide open sky.",
                "A woman of the late Pleistocene–Archaic Americas (c. 15,000–1500 BCE), descended from the first Beringian founders, her long straight hair worn in plaits and her brow touched with ochre, wearing a fringed soft-tanned hide dress sewn with bone needle, a twined plant-fibre apron and woven sandals, a hide robe about her shoulders, and ornaments of bone, shell, seed beads and porcupine quillwork. The full-bleed background is the First Americans' world: a vast wild landscape of open plains, woodland and distant snow-capped peaks, a herd of bison and caribou drifting across the grass, an atlatl spear-thrower with fluted stone points by the camp, conical hide tents, a campfire with meat drying on wooden racks, and migratory game along the far horizon under a wide open sky."),
            ["Ancestral South Indian (10000 - 2000 BC)"] = (
                "A man of the Ancestral South Indian peoples of the peninsular subcontinent (c. 10,000-2000 BCE), lean and weathered, wearing minimal woven plant-fibre and hide garments, his brow and forearms touched with ochre, adorned with strands of ostrich-eggshell, seed, shell and bone beads and simple bangles. The full-bleed background is the Deccan forager world: tropical deciduous forest and granite hills, a hunted blackbuck and wild boar, a bow with microlith-tipped arrows, ground-stone tools, early millet plots and humped zebu cattle, ochre rock-shelter paintings on a stone face, and a thatched shelter by a fire.",
                "A woman of the Ancestral South Indian peoples of the peninsular subcontinent (c. 10,000-2000 BCE), lean and weathered, wearing a minimal plant-fibre and soft-hide skirt-wrap, her skin marked with linear ochre body-painting, adorned as the Bhimbetka figures are: many strands of ostrich-eggshell, seed, shell and bone beads, bangles and wrist, arm and elbow bands, knee-bands with tassels, her hair bound up and dressed with shell and seed ornaments. The full-bleed background is the Deccan forager world: tropical deciduous forest and granite hills, a hunted blackbuck and wild boar, a bow with microlith-tipped arrows, ground-stone tools, early millet plots and humped zebu cattle, ochre rock-shelter paintings on a stone face, and a thatched shelter by a fire."),
            ["Sub Saharan African"] = (
                "A man of an ancient Sub-Saharan African foraging people of deep antiquity (one of humanity's oldest lineages, ancestral San-related) — wearing a soft animal-hide kaross slung over one shoulder and strands of ostrich-eggshell beads at his neck and brow, his hair in tight natural coils. The full-bleed background is the ancient African world: golden savanna and bushland under a wide sky, a hunted antelope, a hunter's bow with poison-tipped arrows and a hide quiver, a digging stick and a gourd, ochre-and-white rock-art figures painted on a stone face, scattered flat-topped acacia trees, and a hearth glowing at the mouth of a rock shelter.",
                "A woman of an ancient Sub-Saharan African foraging people of deep antiquity (one of humanity's oldest lineages, ancestral San-related) — wearing a soft animal-hide kaross worn as a cloak (doubling as a carrying-cape) over a beaded front-and-back leather apron, with abundant ostrich-eggshell bead jewellery: a beaded headband, layered neck and chest strands, and bracelets, her hair in tight natural coils. The full-bleed background is the ancient African world: golden savanna and bushland under a wide sky, a hunted antelope, a hunter's bow with poison-tipped arrows and a hide quiver, a gatherer's weighted digging stick and a gourd, ochre-and-white rock-art figures painted on a stone face, scattered flat-topped acacia trees, and a hearth glowing at the mouth of a rock shelter."),
            ["Illyrian (1200 - 250 BC)"] = (
                "A man of the Iron Age western Balkans (c. 1200-250 BCE) in Illyrian battle gear: a white brimless felt pileus cap - a smooth, perfectly egg-shaped solid half-dome holding its shape, with NO folds, creases, wrinkles or drooping tip - fitted snugly over the crown and tilted slightly back; a white knee-length many-pleated fustanella kilt over a woollen tunic with a short cloak, a wide riveted decorated bronze war-belt, and bronze greaves. The full-bleed background is the Illyrian world: the blue Adriatic crowded with fast low-slung lembos galleys packed with oarsmen and warriors, and along the rocky coast only Hellenistic stone cities - white colonnaded temples, a theatre and stone harbour walls - absolutely NO huts, mud-brick or primitive dwellings anywhere, under a bright Mediterranean sky.",
                "A woman of the Iron Age western Balkans (c. 1200-250 BCE) of Illyrian high standing, heavily draped with bronze and amber adornment as on festive days: a long woven woollen dress pinned at both shoulders with large double-spiral spectacle fibulae and Glasinac bow-brooches, belted at the waist, with a draped headcloth veil over coiled braided hair; a bronze diadem, spiral arm- and leg-rings, serpentine pendants and amber and glass bead strands. The full-bleed background is the Illyrian world: the blue Adriatic crowded with fast low-slung lembos galleys packed with oarsmen and warriors, and along the rocky coast only Hellenistic stone cities - white colonnaded temples, a theatre and stone harbour walls - absolutely NO huts, mud-brick or primitive dwellings, under a bright Mediterranean sky."),
            ["Ancient Greek (1500 - 300 BC)"] = (
                "A man of Classical Athens (5th-4th century BCE), a thoughtful civilian philosopher with a calm expression. He is dressed ONLY in a plain undyed off-white woollen himation draped across one shoulder over a simple linen chiton, in soft folds of cloth, completely unarmoured and unarmed, a teacher and never a soldier (absolutely NO armour, breastplate, cuirass, scale, mail, helmet or weapon on his body). The full-bleed background is the world of Greek philosophy: a sunlit marble colonnaded stoa and the columns of the Academy, an olive grove and cypress around a quiet garden courtyard, papyrus scrolls and a wax tablet on a stone bench, a marble herm and a sundial, robed students conversing in the distance, and the marble temples of the Acropolis on the hill beyond under a calm blue sky.",
                "A woman of Classical Athens (5th-4th century BCE), an elite citizen-wife with a calm, dignified expression. She is dressed ONLY in civilian women's dress: a pleated Ionic linen chiton pinned at the arms and belted at the waist, beneath a draped woollen himation drawn over her head as a veil; her hair is bound into a patterned cloth sakkos with a gold fillet, gold disc earrings and a beaded necklace (absolutely NO armour, helmet or weapon anywhere on her body). The full-bleed background is the world of Greek philosophy: a sunlit colonnaded stoa and the columns of the Academy, an olive grove and cypress around a garden courtyard, scrolls and a wax tablet on a stone bench, a marble herm and a sundial, robed figures in the distance, and the marble temples of the Acropolis under a blue sky."),
            ["Thracian (850 - 0 BC)"] = (
                "A man of the Thracian warrior nobility of the Iron Age eastern Balkans (c. 850 BCE-0), his forearms marked with the traditional geometric tattoos that signal Thracian noble birth, wears a shaggy fox- or bear-skin cap, a brightly patterned woven cloak (the zeira) clasped over a belted tunic, and soft laced hide boots; he is empty-handed and unarmed. The full-bleed background is the Thracian world: rolling oak-forested Balkan hills falling toward the Black Sea coast, mounted Thracian horsemen riding the ridgeline, a grassy tumulus burial mound, glinting gold and silver treasure laid on cloth (an ornate animal-headed rhyton and round phalerae), horses grazing loose, and a hilltop shrine of the Thracian Rider hero beneath a wide sky.",
                "A woman of the Thracian nobility of the Iron Age eastern Balkans (c. 850 BCE-0), her neck and forearms marked with the fine geometric tattoos of a Thracian woman of high birth, wears a long pleated chiton beneath a richly draped, brightly patterned woollen himation mantle; her head is veiled and crowned with a gold diadem, with gold pendant earrings and a heavy gold torc-necklace at her throat. The full-bleed background is the Thracian world: rolling oak-forested Balkan hills falling toward the Black Sea coast, mounted Thracian horsemen riding the ridgeline, a grassy tumulus burial mound, glinting gold and silver treasure laid on cloth (an ornate animal-headed rhyton and round phalerae), horses grazing loose, and a hilltop shrine of the Thracian Rider hero beneath a wide sky."),
            ["Anatolian (1800 - 300 BC)"] = (
                "A man of the Bronze Age Hittite world, his hair gathered at the nape and a neat beard, wearing a long fringed wool tunic belted at the waist. The full-bleed background is the Hittite world packed edge to edge: the cyclopean limestone walls and Lion Gate of Hattusa with sphinx-flanked portals, the rock-cut relief sanctuary of Yazılıkaya carved with long processions of striding gods, a paneled three-man war chariot drawn up nearby, agricultural terracing climbing the windswept Anatolian plateau, herds of cattle grazing across the steppe with herders moving among them, and storm-god stelae bearing horned crowns, under a wide sky with ragged drifting clouds.",
                "A woman of the Bronze Age Hittite world, modestly and fully covered in the manner of Hatti: a long pleated wool robe with loose sleeves falling to the ankles and drawn in at the waist, a tall polos-like crown with a kuressar veil draped over it that flows across her shoulders and back, and a gold diadem with lapis-lazuli and carnelian beads at her throat and bracelets at her wrists. The full-bleed background is the Hittite world packed edge to edge: the cyclopean limestone walls and Lion Gate of Hattusa with sphinx-flanked portals, the rock-cut relief sanctuary of Yazılıkaya carved with processions of gods, a paneled three-man war chariot, terracing on the windswept plateau, herds of cattle with herders, and storm-god stelae bearing horned crowns, under a wide sky with drifting clouds."),
            ["Phoenician (850 - 50 BC)"] = (
                "A man of the seafaring merchant class of Iron Age Tyre, wearing a conical brimless felt cap over oiled curled hair, his beard tightly curled in the eastern manner. He is robed in a long fringed wool tunic dyed deep Tyrian purple with a striped sash at the waist, bronze hoop earrings, a carnelian scarab seal-ring and a faience eye-amulet at his throat. The full-bleed background is the Phoenician world: the walled island city of Tyre with mudbrick towers and the great temple of Melqart, a stone harbour with slipways, beached cedar-hulled merchant galleys and a two-tiered bireme bearing a bronze ram and oxhide-eye prow, heaps of murex shells and shimmering purple-dye vats, glass ampullae and ivory carvings, and the cedar-clad Lebanon hills rising above the blue sea.",
                "A woman of the noble merchant class of Iron Age Tyre, her curled hair bound by a fillet band from which a veil falls over her head, cheeks and shoulders beneath a tall domed headdress. She is enveloped neck to foot in a long wool robe dyed deep Tyrian purple with striped borders, cinched by a knotted girdle, with gold earrings on fine chains, layered bead necklaces, armlets and rings. The full-bleed background is the Phoenician world: the walled island city of Tyre with mudbrick towers and the great temple of Melqart, a stone harbour with slipways, beached cedar-hulled merchant galleys and a two-tiered bireme bearing a bronze ram and oxhide-eye prow, heaps of murex shells and shimmering purple-dye vats, glass ampullae and ivory carvings, and the cedar-clad Lebanon hills above the blue sea."),
            ["Celtic (600 - 50 BC)"] = (
                "A man of the Iron Age Celtic La Tène world — hair lime-washed into stiff spikes, a long drooping moustache and a clean chin — bare-chested with woad-blue swirling tattoos, wearing checkered woven tartan trousers (bracae) and a heavy twisted gold torc at his throat, an iron mail shirt slung over one shoulder. The full-bleed background is the Celtic world: a timber-and-rampart hillfort oppidum on a green hill, thatched round houses, a carnyx war-trumpet, swirling La Tène spiral-and-triskele bronzework, a chariot with two ponies, oak groves, and a stone-carved deity head at a sacred spring.",
                "A woman of the Iron Age Celtic La Tène world, an elite noblewoman dressed as in the Vix and Reinheim graves — hair drawn back beneath a tall felt cap with a draped veil — in a long ankle-length woollen peplos-style gown of checkered twill, pinned at both shoulders with coral-inlaid La Tène spiral fibulae and belted at the waist, a heavy twisted gold torc at her throat, amber and blue-glass bead necklaces, bronze arm-rings and bracelets, a woollen mantle clasped with a fibula. The full-bleed background is the Celtic world: a timber-and-rampart hillfort oppidum on a green hill, thatched round houses, a carnyx war-trumpet, swirling La Tène spiral-and-triskele bronzework, a chariot with two ponies, oak groves, and a stone-carved deity head at a sacred spring."),
            ["Iberian (800 - 50 BC)"] = (
                "A man of the pre-Roman Iberian Spanish Levant, a warrior with hair bound back and worn beneath a fitted sinew cap, dressed in a linen tunic edged with a woven red-and-white border and cinched by a wide bronze belt with a hook clasp. The full-bleed background is the Iberian world: a stone-walled oppidum crowning a dry hilltop above terraced olive groves and wheat fields, mudbrick houses set with painted geometric pottery, the carved limestone Lady of Elche bust and squat stone bull sculptures, esparto-grass slopes, grazing sheep, and a votive sanctuary crowded with small bronze ex-voto figurines.",
                "A woman of the pre-Roman Iberian Spanish Levant, an elite lady in the manner of the Lady of Elche: a long belted tunic and a fringed mantle drawn up as a veil over the head, framed by towering wheel-shaped lateral headdress discs (rodetes) bound by a fillet across the brow, her hair coiled at the sides, and tiers of strung necklaces with amphora-shaped pendants and disc earrings. The full-bleed background is the Iberian world: a stone-walled oppidum crowning a dry hilltop above terraced olive groves and wheat fields, mudbrick houses set with painted geometric pottery, carved limestone busts and squat stone bull sculptures, esparto-grass slopes, grazing sheep, and a votive sanctuary crowded with small bronze ex-voto figurines."),
            ["Carthaginian (800 - 150 BC)"] = (
                "A man of the Carthaginian Punic elite of the western Mediterranean (800-150 BC), an officer wearing a fringed crimson-and-saffron woven tunic with a Tyrian-purple-bordered mantle, gold hoop earrings, a Tanit pendant at his throat, and a bronze-scaled cuirass over linen, his dark hair in oiled ringlets at the temples. The full-bleed background is the Carthaginian world packed edge to edge: the circular cothon war-harbour ringed with ship-sheds and beaked triremes and quinqueremes, the tiered Byrsa citadel, sandstone temples to Baal Hammon and Tanit, a tophet of carved stelae, war elephants with mahouts, amphorae of wine and silver, palms swaying, and the blue Gulf of Tunis under a bright sky.",
                "A woman of the Carthaginian Punic elite of the western Mediterranean (800-150 BC), a noblewoman or priestess wrapped neck-to-foot in a long pleated linen chiton-robe in deep folds beneath a fringed Tyrian-purple-bordered mantle, a fine veil over a diadem in the Egyptianizing Punic style, gold crescent earrings, glass-paste and gold bead necklaces, and a Tanit amulet-case pendant; her hair is bound and draped. The full-bleed background is the Carthaginian world packed edge to edge: the circular cothon war-harbour ringed with ship-sheds and beaked triremes and quinqueremes, the tiered Byrsa citadel, sandstone temples to Baal Hammon and Tanit, a tophet of carved stelae, war elephants with mahouts, amphorae of wine and silver, palms swaying, and the blue Gulf of Tunis under a bright sky."),
            ["Pontic (300 - 50 BC)"] = (
                "A man of the Hellenistic Black Sea coast, a Pontic Greek of the Mithridatic court, wears a fine wool chiton with a draped chlamys cloak pinned at the shoulder by a worked fibula, over the styles of the Mithridatic court: a bronze muscled cuirass with hanging leather pteruges. The full-bleed background is the world of Pontus: the harbor and acropolis of Sinope and Amisos with colonnaded Greek temples and a theater cut into forested hills, the fertile vineyards and chestnut groves of the rugged Paphlagonian coast, fishing boats and grain ships riding the dark Euxine Sea, silver tetradrachm coins bearing a king's portrait, and snow-capped Anatolian mountains rising inland.",
                "A woman of the Hellenistic Black Sea coast, a Pontic Greek noblewoman of the Mithridatic court, wears a fine pleated linen chiton girdled high beneath the bust, with a soft wool himation draped across one shoulder and drawn up as a light veil over her gathered hair; a gold stephane diadem crowns her brow, and she wears gold pendant earrings, a beaded gold necklace and twisted bracelets. The full-bleed background is the world of Pontus: the harbor and acropolis of Sinope and Amisos with colonnaded Greek temples and a theater cut into forested hills, the fertile vineyards and chestnut groves of the rugged Paphlagonian coast, fishing boats and grain ships riding the dark Euxine Sea, silver tetradrachm coins bearing a king's portrait, and snow-capped Anatolian mountains rising inland."),
            ["West Anatolian (0 - 600 AD)"] = (
                "A man of the Roman-era West Anatolian Greek elite of the province of Asia, his hair cut short in the Roman fashion with a neatly trimmed beard, wearing a fine bleached linen tunic under a draped woolen himation pinned at the shoulder with a gold fibula, leather sandals, and a heavy gold signet ring. The full-bleed background is the West Anatolian world: the marble Library of Celsus and the great Temple of Artemis at Ephesus, the terraced Pergamon acropolis with its altar, a colonnaded marble street lined with statues and shops, the harbor of Smyrna crowded with merchant ships, terracotta-roofed villas with mosaic courtyards, and olive groves, vineyards and grazing sheep on sun-baked Aegean hills.",
                "A woman of the Roman-era West Anatolian Greek elite of the province of Asia, her hair dressed in an elaborate updo, wearing an ankle-length fine linen chiton fastened at the shoulders and a draped woolen himation/palla dyed deep cyclamen-purple, adorned in Fayum-portrait fashion with a gilded laurel wreath, a gold-and-emerald necklace, pearl crotalia drop earrings and a gold signet ring. The full-bleed background is the West Anatolian world: the marble Library of Celsus and the great Temple of Artemis at Ephesus, the terraced Pergamon acropolis with its altar, a colonnaded marble street lined with statues and shops, the harbor of Smyrna crowded with merchant ships, terracotta-roofed villas with mosaic courtyards, and olive groves, vineyards and grazing sheep on sun-baked Aegean hills."),
            ["Latin and Etruscan (850 - 150 BC)"] = (
                "A man of Iron Age central Italy, an Etruscan-Italic noble with dark wavy hair and a neatly trimmed pointed beard, wearing a crescent-shaped bronze pectoral cardiophylax over a short bronze-studded linen tunic, with bronze greaves, standing empty-handed. The full-bleed background is the Etruscan world packed edge to edge: a tufa-cut cliffside necropolis of tumulus tombs and carved house-tombs at Cerveteri, terracotta temple roofs crowned with painted antefixes and acroteria, glossy black bucchero pottery and red-figure vases, granulated-gold fibulae and a cast-bronze chimera, and cypress-clad Tuscan hills falling to the Tyrrhenian Sea where merchant ships sail under a bright sky.",
                "A woman of Iron Age central Italy, an Etruscan-Italic noblewoman, her hair in ringlets gathered into a conical tutulus bun, in an ankle-length pleated linen chiton pinned at both shoulders with granulated-gold fibulae and a bordered tebenna mantle, adorned with a gold diadem, baule earrings, a granulated gold pectoral, amber beads and pointed red leather slippers. The full-bleed background is the Etruscan world packed edge to edge: a tufa-cut cliffside necropolis of tumulus tombs and carved house-tombs at Cerveteri, terracotta temple roofs crowned with painted antefixes and acroteria, glossy black bucchero pottery and red-figure vases, granulated-gold fibulae and a cast-bronze chimera, and cypress-clad Tuscan hills falling to the Tyrrhenian Sea where merchant ships sail under a bright sky."),
            ["Moesia Superior (0 - 500 AD)"] = (
                "A man of Moesia Superior on the Danube limes, a Roman provincial legionary, wearing segmented lorica segmentata iron plate over a red tunic, hobnailed caligae, and a knotted balteus belt with apron studs. The full-bleed background is the Moesian world: the legionary fortress of Viminacium with stone walls and a porta praetoria, tiled barracks and a bath-house, the broad grey Danube with patrol liburnian galleys, a milestone road, vineyards on limestone hills, and a Roman tombstone stele beside a temple to Jupiter.",
                "A woman of Moesia Superior on the Danube limes, a Roman provincial matron of standing, wearing a long sleeveless stola suspended by shoulder straps over a fine linen tunica interior, a draped woollen palla shawl pinned with a gilt-bronze fibula and falling from the left shoulder, a provincial Danubian bonnet-style headdress over hair dressed in waves, and pectoral jewellery, gold hoop earrings, a torque, and rings. The full-bleed background is the Moesian world: the legionary fortress of Viminacium with stone walls and a porta praetoria, tiled barracks and a bath-house, the broad grey Danube with patrol liburnian galleys, a milestone road, vineyards on limestone hills, and a Roman tombstone stele beside a temple to Jupiter."),
            ["Eastern Mediterranean (0 - 600 AD)"] = (
                "A man of the Roman-provincial Levantine elite, an adult with a trimmed beard, wearing a long fringed wool tunic and a draped striped mantle dyed with Tyrian purple, a round fibula brooch pinning it at the shoulder, leather sandals, and a heavy gold signet ring and torque. The full-bleed background is the Roman-Levantine world of a caravan city like Palmyra or Apamea: a colonnaded cardo and monumental tetrapylon, a sandstone temple of Bel with Corinthian capitals, mosaic-paved courtyards and a Roman aqueduct, amphorae of wine and olive oil stacked by a busy harbor, laden camel caravans on the trade road, date palms and parched desert hills, and a carved limestone funerary bust set in a tower-tomb under a hot blue sky.",
                "A woman of the Roman-provincial Levantine elite, a noblewoman of a caravan city, wearing a long fine wool tunic beneath a mantle fastened on the left shoulder with a round gold fibula, her head bound in a turban with a central loop and draped in a long veil, over center-parted wavy hair; she wears a jeweled diadem and brow-band with a head-chain, large pendant earrings, several pearl-and-bead necklaces, bracelets, and rings. The full-bleed background is the Roman-Levantine world of a city like Palmyra or Apamea: a colonnaded cardo and tetrapylon, a sandstone temple of Bel with Corinthian capitals, mosaic courtyards and a Roman aqueduct, amphorae by a busy harbor, laden camel caravans, date palms and desert hills, and a carved limestone funerary bust in a tower-tomb under a hot blue sky."),
            ["Germanic (0 - 500 AD)"] = (
                "A man of the Migration-Period Germanic peoples, his long hair pulled into a Suebian knot at the temple and worn with a braided beard, in a knee-length woollen tunic with tablet-woven trim under a riveted mail shirt, leather cross-gartered trousers, an annular brooch and a gilt-bronze belt fitting, standing empty-handed. The full-bleed background is the Germanic world edge to edge: a great timber longhouse with thatched roof and carved gable-beasts amid a misty pine-and-birch forest, a clinker-built oared boat drawn up on a grey fjord shore, standing runestones beside a heaped barrow grave, grazing cattle, and a sacred grove hung with offerings.",
                "A woman of the Migration-Period Germanic peoples, her hair bound up and partly draped under a woven veil, in a long tubular woollen peplos overdress suspended from the shoulders by a pair of gilt-bronze bow brooches linked across the chest by a festoon of glass and amber beads, worn over a long-sleeved linen underdress with a keyhole neckline closed by a small brooch; a strung bead necklace, spiral bronze arm-rings and a tablet-woven belt complete the elite dress. The full-bleed background is the Germanic world edge to edge: a great timber longhouse with thatched roof and carved gable-beasts amid a misty pine-and-birch forest, a clinker-built oared boat drawn up on a grey fjord shore, standing runestones beside a heaped barrow grave, grazing cattle, and a sacred grove hung with offerings."),
            ["Early Slavic (600 - 1200 AD)"] = (
                "A man of the early medieval Eastern European forests, lightly weathered, his hair worn long, in a knee-length belted linen tunic and woollen leg-wrappings with leather lace-up shoes, and a coarse wool cloak pinned at one shoulder by a simple iron brooch. The full-bleed background is the early Slavic world filling the frame: a stockaded gord hillfort of timber ramparts above the river, sunken-floored grubenhaus huts with thatched roofs and rising smoke, hand-thrown Prague-type pottery and bone tools, dugout logboats on the water, stern oak idols of Perun, livestock grazing, and dark birch-and-pine woodland under a pale northern sky.",
                "A woman of the early medieval Eastern European forests, lightly weathered, her hair in braids under a linen kerchief, in a long natural-linen underdress with tapered sleeves worn beneath a striped woollen apron-skirt belted at the waist, with leather lace-up shoes; looped bronze temple rings hang at her headband, glass and amber beads circle her throat, and a small ring brooch fastens her wool wrap. The full-bleed background is the early Slavic world filling the frame: a stockaded gord hillfort of timber ramparts above the river, sunken-floored grubenhaus huts with thatched roofs and rising smoke, hand-thrown Prague-type pottery and bone tools, dugout logboats on the water, stern oak idols of Perun, livestock grazing, and dark birch-and-pine woodland under a pale northern sky."),
            ["North African (0 - 500 AD)"] = (
                "A man of the Roman-era Berber (Amazigh) people of North Africa, with a faint curved facial tattoo on his cheek in the Amazigh tradition, draped in a thick striped woolen burnous over a desert-toned tunic pinned at the shoulder with a bronze fibula. The full-bleed background is the Berber and Roman provincial world: the colonnaded marble streets and theatre of Leptis Magna, a triumphal arch and the harbour of Carthage, mudbrick fortified granaries and tiered ksar villages, a pre-Saharan oasis with date palms, dromedary camels and tethered Barbary horses, mosaic-floored villas, and rolling olive groves above the blue Mediterranean coast.",
                "A woman of the Roman-era Berber (Amazigh) people of North Africa, with a faint Amazigh chin tattoo, her hair bound under a draped woollen headscarf-veil. She wears a large rectangular woollen wrap worn toga-like over a belted undertunic, pinned at both shoulders by a pair of big triangular silver Amazigh fibulae linked by a chest chain, with twisted silver neck-rings and coral-and-silver beads. The full-bleed background is the Berber and Roman provincial world: the colonnaded marble streets and theatre of Leptis Magna, a triumphal arch and the harbour of Carthage, mudbrick fortified granaries and tiered ksar villages, a pre-Saharan oasis with date palms, dromedary camels and tethered Barbary horses, mosaic-floored villas, and rolling olive groves above the blue Mediterranean coast."),
            ["Baltic (BC 200 - 600 AD)"] = (
                "A man of the eastern Baltic Iron Age proto-Balt tribes, his long hair worn loose and his beard trimmed, dressed in a woven woolen tunic and a cloak fastened at the shoulder with a large crossbow-style bronze fibula and ringed penannular brooches, his neck and chest hung with twisted bronze neck-rings and strands of amber beads. The full-bleed background is the Baltic world: a timber-palisaded earthwork hillfort rising above dense pine and oak forest, sunken log dwellings with thatched roofs, dugout fishing canoes drawn up on a misty Baltic shore strewn with raw golden amber, grazing cattle, and a cremation burial field of low mounds.",
                "A woman of the eastern Baltic Iron Age proto-Balt tribes, her hair bound beneath a bronze-spiral chaplet and a coiled headband, dressed in a long linen shift under a dark blue woolen wrap-skirt and a shawl whose hems are sewn with rows of tiny bronze spirals, the shawl pinned across her chest with a crossbow-style bronze fibula and ringed penannular brooches. Her adornments are a twisted bronze neck-ring with hooked terminals, spiral arm-rings and finger-rings, and strands of amber and glass beads. The full-bleed background is the Baltic world: a timber-palisaded earthwork hillfort above dense pine and oak forest, sunken log dwellings with thatched roofs, dugout canoes on a misty Baltic shore strewn with raw golden amber, grazing cattle, and a cremation burial field of low mounds."),
            ["Finno-Ugric Volga (0 - 400 AD)"] = (
                "A man of the Iron Age Volga-Kama forests in a belted woollen tunic and elk-hide leggings under a fur-trimmed cloak, hung with rattling cast-bronze pendants, hollow jingling bells, spiral and waterfowl ornaments and a chest plaque of clasped bronze; his hair worn long. The full-bleed background is the Finno-Ugric Volga world: a palisaded hilltop settlement of timber log dwellings above the wide Kama and Volga rivers, dark spruce-and-birch taiga, smoking bronze-casting hearths and clay moulds, tethered horses and cattle, dugout canoes, fur pelts drying, and earthen burial mounds rich with bronze grave-goods.",
                "A woman of the Iron Age Volga-Kama forests, high-status, in a long belted woollen dress edged with rows of sewn bronze spirals over a linen underdress and a fur-trimmed cloak pinned at the shoulder, a tall birch-bark headdress with a beaded veil and chiming bronze temple-rings, her hair coiled beneath. She wears the noise-jewellery of the Volga Finns: a bronze torc, bead strands, a round breast-plaque, and a fringed apron of rattling waterfowl pendants and bells. The full-bleed background is the Finno-Ugric Volga world: a palisaded hilltop settlement of timber log dwellings above the wide Kama and Volga rivers, dark spruce-and-birch taiga, smoking bronze-casting hearths and clay moulds, tethered horses and cattle, dugout canoes, drying fur pelts, and earthen mounds of bronze grave-goods."),
            ["Saami (0 - 700 AD)"] = (
                "A man of the Iron Age Saami of northern Fennoscandia, dressed in a reindeer-hide tunic and leggings sewn with sinew, a four-winds-style peaked hide hat trimmed with red and yellow woven bands, a pewter-thread-embroidered belt, and curl-toed reindeer-fur boots stuffed with sedge grass; at his neck hang strands of beads and rattling cast-bronze pendants. The full-bleed background is the Saami world: a conical lavvu of poles and hides, a domesticated reindeer herd grazing lichen on snowy tundra, a goahti turf hut, a flat oval shaman's drum painted with sun-symbols, birch-and-pine taiga, a frozen lake, and gákti-pattern reds against pale Arctic light.",
                "A woman of the Iron Age Saami of northern Fennoscandia, dressed in a long belted reindeer-hide dress sewn with sinew, its high collar, cuffs and waist worked with pewter-thread embroidery in red and yellow woven bands, a fringed woven shawl over her shoulders pinned with round bronze brooches; she wears a soft hide-and-woven cap, her hair long beneath it, her chest hung with bead strands and jingling cast-bronze pendants, with curl-toed reindeer-fur boots stuffed with sedge grass. The full-bleed background is the Saami world: a conical lavvu of poles and hides, a domesticated reindeer herd grazing lichen on snowy tundra, a goahti turf hut, a flat oval shaman's drum painted with sun-symbols, birch-and-pine taiga, a frozen lake, and gákti-pattern reds against pale Arctic light."),
            ["Imperial Italy (0 - 550 AD)"] = (
                "A man of Imperial Roman Italy, a legionary in lorica segmentata of overlapping iron plates over a deep-red wool tunic, a military belt with hanging apron studs, and hobnailed caligae sandals; a gladius at his hip. The full-bleed background is the Roman world: the travertine arches of the Colosseum and a Corinthian-columned forum, a triumphal arch and a great aqueduct striding the Campagna, marble temples with brightly painted statues, terracotta-tiled insulae and country villas among dark cypress, terraced vineyards and silvery olive groves, a golden eagle aquila standard raised on its pole, and an oared galley with a furled sail riding the Tiber under a clear Mediterranean sky.",
                "A woman of Imperial Roman Italy, a matron in a long pleated stola of bleached wool belted high beneath the bust over an undertunic, draped in a saffron-bordered palla mantle drawn over the head as a veil; her hair is dressed in matron's curls bound with woolen vittae fillets, with gold drop earrings, a beaded gold necklace, a fibula brooch and signet rings. The full-bleed background is the Roman world: the travertine arches of the Colosseum and a Corinthian-columned forum, a triumphal arch and a great aqueduct striding the Campagna, marble temples with painted statues, terracotta-tiled insulae and villas among dark cypress, terraced vineyards and silvery olive groves, a golden eagle aquila standard, and an oared galley with a furled sail riding the Tiber under a clear Mediterranean sky."),
            ["Aegean (BC 200 - 600 AD)"] = (
                "A man of the Hellenistic Aegean Greek world, draped in a fine bleached-wool himation worn over a belted chiton, fastened with a fibula brooch at the shoulder, a laurel wreath on his brow and a bronze signet ring on his hand. The full-bleed background is the Greek world: a gleaming white marble temple with fluted Ionic columns and a painted pediment on a rocky acropolis, a bustling harbour town of tiled stoas and an agora lined with bronze statues, terraced vineyards and silvery olive groves on sun-baked hillsides, painted black-and-red figure amphorae and a marble herm, and merchant galleys with furled sails and oars riding the deep-blue Aegean.",
                "A woman of the Hellenistic Aegean Greek world, in a fine pleated linen Ionic chiton pinned along the arms, a soft bleached-wool himation draped across her body and drawn up over her head as a veil, her hair dressed in a melon coiffure gathered into a low bun beneath a slender gold stephane, adorned with gold disc earrings, a beaded necklace and a coiled snake bracelet. The full-bleed background is the Greek world: a gleaming white marble temple with fluted Ionic columns and a painted pediment on a rocky acropolis, a bustling harbour town of tiled stoas and an agora lined with bronze statues, terraced vineyards and silvery olive groves on sun-baked hillsides, painted black-and-red figure amphorae and a marble herm, and merchant galleys with furled sails and oars riding the deep-blue Aegean."),
            ["Proto Albanian (500 - 900 AD)"] = (
                "A man of the medieval western Balkans, hair loose to the shoulders, completely BARE-HEADED — no helmet, hood or head-covering. He wears a FULL suit of knight's plate armour — breastplate, pauldrons, vambraces and gauntlets — with chain mail over a plain single-colour surcoat. Armour and surcoat are completely BLANK: NO flag, double-headed eagle, emblem or symbol anywhere. The full-bleed background is the Albanian world: a stone hilltop castle of crenellated towers and a keep above rugged mountains toward the Adriatic, flying one large modern Albanian flag (deep red, black double-headed eagle) from its top — the ONLY flag or eagle anywhere, never on the man; dry-stone battlements, terraced slopes grazed by sheep and goats, and a stone basilica with apses on the karst hill.",
                "A woman of the medieval western Balkans, an elite Komani-Kruja noblewoman in authentic dress: a long linen chemise under a woollen overgown belted with a bronze buckle, a mantle pinned with cast bronze bow-fibulae, hair veiled in a linen head-cloth, with a glass-bead necklace, gilded-bronze Byzantine earrings and bronze rings — but NO double-headed eagle, emblem or symbol anywhere. The full-bleed background is the Albanian world: a stone hilltop castle of crenellated towers and a keep above rugged mountains toward the Adriatic, flying one large modern Albanian flag (deep red, black double-headed eagle) from its top — the ONLY flag or eagle anywhere, never on the woman; dry-stone battlements, terraced slopes grazed by sheep and goats, and a stone basilica with apses on the karst hill."),

        };
}
